# Generated by Django 4.2.17 on 2026-03-08 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sellers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("universities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerDashboardStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_commission_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_orders", models.IntegerField(default=0)),
                ("completed_orders", models.IntegerField(default=0)),
                (
                    "pending_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "rating_avg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("last_computed_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_stats",
                        to="sellers.sellerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "seller_dashboard_stats",
            },
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "search_scope",
                    models.CharField(
                        choices=[
                            ("mall", "Mall"),
                            ("marketplace", "Marketplace"),
                            ("all", "All"),
                        ],
                        max_length=15,
                    ),
                ),
                ("query", models.CharField(max_length=300)),
                ("result_count", models.IntegerField(default=0)),
                ("searched_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="universities.university",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "search_logs",
                "indexes": [
                    models.Index(
                        fields=["university", "searched_at"],
                        name="search_logs_univers_73efb4_idx",
                    ),
                    models.Index(fields=["query"], name="search_logs_query_5b6409_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_id", models.UUIDField(db_index=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[("mall", "Mall"), ("marketplace", "Marketplace")],
                        max_length=15,
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("viewed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="universities.university",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "product_views",
                "indexes": [
                    models.Index(
                        fields=["product_id", "product_type", "viewed_at"],
                        name="product_vie_product_9d5af7_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("module", models.CharField(db_index=True, max_length=50)),
                (
                    "resource_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("resource_id", models.UUIDField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activity_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "action", "created_at"],
                        name="activity_lo_user_id_9a0a50_idx",
                    ),
                    models.Index(
                        fields=["module", "created_at"],
                        name="activity_lo_module_b6aeec_idx",
                    ),
                ],
            },
        ),
    ]
