# Generated by Django 4.2.17 on 2026-03-07 18:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="When this record was soft-deleted. NULL means active.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full official name of the university.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Abbreviation, e.g. 'DIU'.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-safe identifier, auto-generated from short_name.",
                        max_length=25,
                        unique=True,
                    ),
                ),
                (
                    "system_id",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated system ID: UNIV-00001.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        choices=[
                            ("Dhaka", "Dhaka"),
                            ("Chittagong", "Chittagong"),
                            ("Rajshahi", "Rajshahi"),
                            ("Khulna", "Khulna"),
                            ("Barisal", "Barisal"),
                            ("Sylhet", "Sylhet"),
                            ("Rangpur", "Rangpur"),
                            ("Mymensingh", "Mymensingh"),
                        ],
                        help_text="Administrative division where the university is located.",
                        max_length=20,
                    ),
                ),
                (
                    "district",
                    models.CharField(help_text="District name.", max_length=80),
                ),
                (
                    "postal_code",
                    models.CharField(
                        help_text="Postal code of the university area.", max_length=10
                    ),
                ),
                (
                    "full_address",
                    models.TextField(
                        help_text="Complete street address of the university."
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Brief description of the university.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the university logo image.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this university is currently active on the platform.",
                    ),
                ),
                (
                    "sso_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether SSO login is enabled for this university.",
                    ),
                ),
                (
                    "sso_provider",
                    models.CharField(
                        blank=True,
                        help_text="SSO provider type: 'google', 'microsoft', 'saml'.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "sso_domain",
                    models.CharField(
                        blank=True,
                        help_text="Email domain for SSO, e.g. '@diu.edu.bd'.",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "University",
                "verbose_name_plural": "Universities",
                "db_table": "universities",
                "ordering": ["name"],
                "abstract": False,
                "indexes": [
                    models.Index(fields=["slug"], name="idx_univ_slug"),
                    models.Index(fields=["short_name"], name="idx_univ_short_name"),
                    models.Index(fields=["is_active"], name="idx_univ_is_active"),
                ],
            },
        ),
    ]
