# Generated by Django 4.2.17 on 2026-03-07 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the JWT access token.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "device_info",
                    models.CharField(
                        blank=True,
                        help_text="User-Agent or device description.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address the session was created from.",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, help_text="When this session token expires."
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this session has been revoked.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this session.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "db_table": "auth_user_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Label for this address, e.g. 'Home', 'Dorm', 'Campus'.",
                        max_length=100,
                    ),
                ),
                ("address_line1", models.TextField(help_text="Primary address line.")),
                (
                    "address_line2",
                    models.TextField(
                        blank=True,
                        help_text="Secondary address line (optional).",
                        null=True,
                    ),
                ),
                (
                    "campus_building",
                    models.CharField(
                        blank=True,
                        help_text="Campus building name (if applicable).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True,
                        help_text="Room number (if applicable).",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "district",
                    models.CharField(help_text="District name.", max_length=80),
                ),
                ("city", models.CharField(help_text="City name.", max_length=100)),
                (
                    "postal_code",
                    models.CharField(help_text="Postal code.", max_length=10),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Whether this is the default address."
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Soft deletion timestamp.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this address.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Address",
                "verbose_name_plural": "User Addresses",
                "db_table": "auth_user_addresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("student_id", "Student ID"),
                            ("faculty_id", "Faculty ID"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                        ],
                        help_text="Type of verification being submitted.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current verification status.",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_document_url",
                    models.CharField(
                        blank=True,
                        help_text="S3 private bucket path for the submitted document.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "student_id_number",
                    models.CharField(
                        blank=True,
                        help_text="Student or faculty ID number.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "enrollment_cert_url",
                    models.CharField(
                        blank=True,
                        help_text="S3 private bucket path for enrollment certificate.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "verification_tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                        ],
                        default="bronze",
                        help_text="Verification tier level.",
                        max_length=10,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection, shown to the user.",
                        null=True,
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Expiration date for this verification (annual renewal).",
                        null=True,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Soft deletion timestamp.",
                        null=True,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this verification.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting verification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Verification",
                "verbose_name_plural": "User Verifications",
                "db_table": "auth_user_verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="idx_verification_user_status"
                    ),
                    models.Index(
                        fields=["user", "verification_type"],
                        name="idx_verification_user_type",
                    ),
                ],
                "unique_together": {("user", "verification_type")},
            },
        ),
    ]
