# Generated by Django 4.2.17 on 2026-03-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_usersession_useraddress_userverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("normal_user", "Normal User"),
                    ("student", "Student"),
                    ("faculty", "Faculty"),
                    ("seller", "Seller"),
                    ("moderator", "Moderator"),
                    ("admin", "Admin"),
                ],
                db_index=True,
                default="normal_user",
                help_text="System role determining access rights.",
                max_length=20,
            ),
        ),
    ]
