# Generated by Django 4.2.17 on 2026-04-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_otpcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpcode",
            name="purpose",
            field=models.CharField(
                choices=[("login", "Login"), ("password_reset", "Password Reset")],
                default="login",
                help_text="Why this OTP was issued.",
                max_length=20,
            ),
        ),
    ]
