# Generated by Django 4.2.17 on 2026-05-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_add_seller_mod_marketplace_mod_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(
                blank=True, help_text="Date of birth (optional).", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="First name (Daraz-style profile).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                help_text="Gender (optional).",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Last name (Daraz-style profile).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="additional_notes",
            field=models.TextField(
                blank=True,
                help_text="Additional delivery instructions (optional).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="area",
            field=models.CharField(
                blank=True,
                help_text="Area / Upazila / Thana.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="division",
            field=models.CharField(
                blank=True,
                help_text="Division name (e.g. Dhaka, Chittagong).",
                max_length=80,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="landmark",
            field=models.CharField(
                blank=True,
                help_text="Nearby landmark for easier delivery (optional).",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="recipient_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the person receiving deliveries at this address.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="recipient_phone",
            field=models.CharField(
                blank=True,
                help_text="Recipient phone number for delivery contact.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                help_text="Full name of the user (auto-synced from first_name + last_name when both are set).",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="address_line1",
            field=models.TextField(
                help_text="Primary address line (street, road, house number)."
            ),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="city",
            field=models.CharField(help_text="City / Region.", max_length=100),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="label",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("hostel", "Hostel"),
                    ("office", "Office"),
                    ("campus", "Campus"),
                    ("other", "Other"),
                ],
                default="home",
                help_text="Label for this address.",
                max_length=20,
            ),
        ),
    ]
