# Generated by Django 4.2.17 on 2026-05-02 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_user_birthday_user_first_name_user_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="university_email",
            field=models.EmailField(
                blank=True,
                help_text="University-issued email (used for student/faculty verification).",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="EmailChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "old_email",
                    models.EmailField(
                        help_text="Email at the time the request was created (audit only).",
                        max_length=255,
                    ),
                ),
                (
                    "new_email",
                    models.EmailField(
                        help_text="Address the user wants to switch to.", max_length=255
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Secure random token sent to the new email.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Expiration time for this token."),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Whether this token has been consumed."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this request was created."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who initiated the change.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Change Request",
                "verbose_name_plural": "Email Change Requests",
                "db_table": "auth_email_change_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
