# Generated by Django 4.2.17 on 2026-03-07 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("universities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="When this record was soft-deleted. NULL means active.",
                        null=True,
                    ),
                ),
                ("business_name", models.CharField(max_length=200)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("student", "Student"),
                            ("club", "Club"),
                            ("business", "Business"),
                            ("brand", "Brand"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nid_number", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nid_front_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "nid_back_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "trade_license_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "tin_cert_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "vat_cert_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "brand_auth_letter_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "trademark_cert_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("bank_account_details", models.TextField(blank=True, null=True)),
                (
                    "mobile_banking_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("rocket", "Rocket"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "mobile_banking_number",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("business_phone", models.CharField(max_length=20)),
                (
                    "business_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                ("is_student_seller", models.BooleanField(default=False)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_sellers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "seller_profiles",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudentBenefit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="When this record was soft-deleted. NULL means active.",
                        null=True,
                    ),
                ),
                (
                    "benefit_type",
                    models.CharField(
                        choices=[
                            ("commission_discount", "Commission Discount"),
                            ("free_listing", "Free Listing"),
                            ("priority_ranking", "Priority Ranking"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="granted_benefits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="sellers.sellerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "student_benefits",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="When this record was soft-deleted. NULL means active.",
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField()),
                ("logo_url", models.CharField(blank=True, max_length=500, null=True)),
                ("banner_url", models.CharField(blank=True, max_length=500, null=True)),
                ("store_category", models.CharField(max_length=100)),
                ("return_policy", models.TextField()),
                ("avg_dispatch_hours", models.IntegerField(default=24)),
                ("shipping_coverage", models.TextField(blank=True, null=True)),
                ("business_phone", models.CharField(max_length=20)),
                (
                    "business_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("under_review", "Under Review"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "rating_avg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("review_count", models.IntegerField(default=0)),
                ("total_sales_count", models.IntegerField(default=0)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store",
                        to="sellers.sellerprofile",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="universities.university",
                    ),
                ),
            ],
            options={
                "db_table": "stores",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SellerPayoutRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="When this record was soft-deleted. NULL means active.",
                        null=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("bank", "Bank Transfer"),
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("rocket", "Rocket"),
                        ],
                        max_length=10,
                    ),
                ),
                ("account_details_snapshot", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "bank_transaction_ref",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_requests",
                        to="sellers.sellerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "seller_payout_requests",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SellerBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("student_seller", "Student Seller"),
                            ("verified_seller", "Verified Seller"),
                            ("official_store", "Official Store"),
                            ("best_seller", "Best Seller"),
                            ("club_seller", "Club Seller"),
                            ("fast_dispatch", "Fast Dispatch"),
                        ],
                        max_length=20,
                    ),
                ),
                ("display_label", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("awarded_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="sellers.store",
                    ),
                ),
            ],
            options={
                "db_table": "seller_badges",
                "ordering": ["-awarded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sellerprofile",
            index=models.Index(
                fields=["status", "is_student_seller"],
                name="seller_prof_status_31c833_idx",
            ),
        ),
    ]
