# Generated by Django 4.2.17 on 2026-03-08 13:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerprofile",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
    ]
