# Generated by Django 4.2.17 on 2026-04-24 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sellers", "0002_add_financial_field_validators"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="follower_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="store",
            name="response_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Percentage of messages responded to within 24 hours.",
                max_digits=5,
            ),
        ),
        migrations.CreateModel(
            name="StoreFollower",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="sellers.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed_stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store_followers",
                "ordering": ["-created_at"],
                "unique_together": {("store", "user")},
            },
        ),
    ]
