# Generated by Django 4.2.17 on 2026-05-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0003_store_follower_count_store_response_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="identity_doc_type",
            field=models.CharField(
                blank=True,
                choices=[("nid", "National ID"), ("passport", "Passport")],
                default="nid",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="student_id_card_url",
            field=models.CharField(
                blank=True,
                help_text="Student ID card photo (only for student sellers).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="facebook_page",
            field=models.URLField(
                blank=True,
                help_text="Facebook page URL (optional).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="store_address",
            field=models.TextField(
                blank=True,
                help_text="Physical store address (only relevant for physical / both).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="store_type",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("physical", "Physical"),
                    ("both", "Both Online and Physical"),
                ],
                default="online",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="store",
            name="return_policy",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="store",
            name="store_category",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
