# Generated by Django 4.2.17 on 2026-03-08 09:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="When this record was soft-deleted. NULL means active.",
                        null=True,
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("picked_up", "Picked Up"),
                            ("in_transit", "In Transit"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("returned", "Returned"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("estimated_delivery_date", models.DateField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_proof_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "deliveries",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeliveryPartner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="When this record was soft-deleted. NULL means active.",
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("external_courier", "External Courier"),
                            ("internal", "Internal"),
                            ("campus_runner", "Campus Runner"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "api_endpoint",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "api_key_encrypted",
                    models.TextField(
                        blank=True, help_text="Fernet-encrypted API key.", null=True
                    ),
                ),
                (
                    "tracking_url_template",
                    models.CharField(
                        blank=True,
                        help_text="Template with {code} placeholder.",
                        max_length=300,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("supported_areas", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "delivery_partners",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeliveryTrackingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status_label", models.CharField(max_length=100)),
                (
                    "location_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("event_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="delivery.delivery",
                    ),
                ),
            ],
            options={
                "db_table": "delivery_tracking_events",
                "ordering": ["-event_time"],
            },
        ),
        migrations.AddField(
            model_name="delivery",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deliveries",
                to="delivery.deliverypartner",
            ),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(
                fields=["status", "tracking_code"], name="deliveries_status_ea55f5_idx"
            ),
        ),
    ]
