# Generated by Django 4.2.17 on 2026-05-02 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("rocket", "Rocket"),
                            ("upay", "Upay"),
                            ("tap", "Tap"),
                            ("card", "Credit / Debit Card"),
                            ("bank", "Bank Account"),
                        ],
                        help_text="Type of payment method.",
                        max_length=10,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional nickname like 'My personal bKash'.",
                        max_length=100,
                    ),
                ),
                (
                    "account_holder_name",
                    models.CharField(
                        blank=True,
                        help_text="Name on the account / card.",
                        max_length=200,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="Phone number for mobile wallets, account number for bank, last 4 for card.",
                        max_length=50,
                    ),
                ),
                ("card_last4", models.CharField(blank=True, max_length=4)),
                ("card_brand", models.CharField(blank=True, max_length=20)),
                (
                    "card_expiry",
                    models.CharField(
                        blank=True,
                        help_text="MM/YYYY — used for display only, gateway is the source of truth.",
                        max_length=7,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default payment method.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Soft deletion timestamp.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of this saved payment method.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Payment Method",
                "verbose_name_plural": "User Payment Methods",
                "db_table": "user_payment_methods",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
    ]
