# Generated by Django 4.2.17 on 2026-03-08 04:22

from django.conf import settings
import django.contrib.postgres.indexes
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sellers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(
                        blank=True,
                        help_text="Coupon code (placeholder until coupons app, Phase 08).",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
                "db_table": "mall_carts",
            },
        ),
        migrations.CreateModel(
            name="MallCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="When this record was soft-deleted. NULL means active.",
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Hierarchy level: 1=Main, 2=Sub, 3=Sub-Sub.",
                    ),
                ),
                ("icon_url", models.CharField(blank=True, max_length=300, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="mall.mallcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mall Category",
                "verbose_name_plural": "Mall Categories",
                "db_table": "mall_categories",
                "ordering": ["level", "sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StoreProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="When this record was soft-deleted. NULL means active.",
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=320, unique=True)),
                ("description", models.TextField()),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(
                        default=0,
                        help_text="Total stock. Auto-updated from variants if has_variants=True.",
                    ),
                ),
                ("has_variants", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("weight_grams", models.IntegerField(blank=True, null=True)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tag list, e.g. ['laptop', 'gaming', 'asus'].",
                    ),
                ),
                (
                    "rating_avg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("review_count", models.IntegerField(default=0)),
                ("sold_count", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="mall.mallcategory",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="sellers.store",
                    ),
                ),
            ],
            options={
                "db_table": "mall_store_products",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StoreProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                ("image_url", models.CharField(max_length=500)),
                ("alt_text", models.CharField(blank=True, max_length=200, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="mall.storeproduct",
                    ),
                ),
            ],
            options={
                "db_table": "mall_store_product_images",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="When this record was soft-deleted. NULL means active.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name, e.g. 'Red / XL'.", max_length=100
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Override price. Falls back to product base_price if null.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("stock_quantity", models.IntegerField(default=0)),
                (
                    "attributes",
                    models.JSONField(
                        help_text="Variant attributes, e.g. {'color':'Red','size':'XL'}."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="mall.storeproduct",
                    ),
                ),
            ],
            options={
                "db_table": "mall_product_variants",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="When this record was soft-deleted. NULL means active.",
                        null=True,
                    ),
                ),
                (
                    "order_item_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the OrderItem (from orders app). Linked in Phase 07.",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("seller_response", models.TextField(blank=True, null=True)),
                ("seller_responded_at", models.DateTimeField(blank=True, null=True)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="mall.storeproduct",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mall_reviews_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mall_product_reviews",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price at the time of adding to cart.",
                        max_digits=10,
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="mall.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="mall.storeproduct",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cart_items",
                        to="mall.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "mall_cart_items",
            },
        ),
        migrations.AddIndex(
            model_name="storeproduct",
            index=models.Index(
                fields=["store", "is_active"], name="mall_store__store_i_d382bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storeproduct",
            index=models.Index(
                fields=["category", "is_active"], name="mall_store__categor_45f572_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storeproduct",
            index=models.Index(
                fields=["is_featured"], name="mall_store__is_feat_e55a58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storeproduct",
            index=models.Index(
                fields=["is_active"], name="mall_store__is_acti_d5a321_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storeproduct",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["tags"], name="mall_store__tags_c41b6b_gin"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together={("product", "reviewer")},
        ),
        migrations.AddIndex(
            model_name="mallcategory",
            index=models.Index(
                fields=["parent", "is_active"], name="mall_catego_parent__fb4a5c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product", "variant")},
        ),
    ]
