# Generated by Django 4.2.17 on 2026-05-04 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mall", "0003_banner_brand_storeproduct_view_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated."
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="When this record was soft-deleted. NULL means active.",
                        null=True,
                    ),
                ),
                ("question", models.TextField(max_length=500)),
                ("answer", models.TextField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("is_visible", models.BooleanField(default=True)),
                ("vote_count", models.IntegerField(default=0)),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_questions_answered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_questions_asked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="mall.storeproduct",
                    ),
                ),
            ],
            options={
                "db_table": "mall_product_questions",
                "ordering": ["-vote_count", "-created_at"],
                "abstract": False,
            },
        ),
    ]
