# Generated by Django 4.2.17 on 2026-05-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0004_productquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="evidence_urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of image URLs provided by the buyer for this review.",
            ),
        ),
    ]
