# Generated by Django 4.2.17 on 2026-05-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refunds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="refund",
            name="seller_response",
            field=models.CharField(
                blank=True,
                choices=[("accepted", "Accepted"), ("disputed", "Disputed")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="seller_response_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
